# Generated by Django 3.0.4 on 2020-03-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='bill_ref_number',
            new_name='ref_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_date',
        ),
    ]
